config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  
  resources :users , only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
   validates_uniqueness_of :book_id, scope: :user_id

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #redirect_back(fallback_location: root_path)
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_button.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), remote:true, method: :delete do %>
      ♥<%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), remote:true, method: :post do %>
      ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
  $(".favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/button', book: @book) %>");

app/views/favorites/destroy.js.erb
  $(".favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/button', book: @book) %>");